[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sysvar = "Et8abEv4sHEYXwjGf85o5hdQLTPqP8viVW5LmVeKZmoe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jesserc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
